[project]
name = 'Tokenized-Public-Infrastructure-Asset-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.asset-registry]
path = 'contracts/asset-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.condition-assessment]
path = 'contracts/condition-assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.investment-prioritization]
path = 'contracts/investment-prioritization.clar'
clarity_version = 2
epoch = 2.5

[contracts.maintenance-planning]
path = 'contracts/maintenance-planning.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-monitoring]
path = 'contracts/performance-monitoring.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
